// frontend/src/components/PlaybookExecutor.tsx
'use client'

import { useState, useEffect, useRef, useCallback, forwardRef, useImperativeHandle } from 'react'
import { Loader2, Copy, Check } from 'lucide-react'
import {
  TkDialogRoot,
  TkDialogContent,
  TkDialogHeader,
  TkDialogTitle,
  TkDialogFooter,
} from 'thinkube-style/components/modals-overlays'
import { TkButton } from 'thinkube-style/components/buttons-badges'
import { TkSwitch, TkLabel } from 'thinkube-style/components/forms-inputs'
import { TkSuccessAlert, TkErrorAlert, TkInfoAlert } from 'thinkube-style/components/feedback'
import { TkCard, TkCardContent } from 'thinkube-style/components/cards-data'
import { getAnsibleLogClassName, getAnsibleLogPrefix, AnsibleLogType } from 'thinkube-style/lib/ansible-log-utils'

interface PlaybookExecutorProps {
  title: string
  websocketPath?: string
  deploymentId?: string
  successMessage?: string
  onRetry?: () => void
  onComplete?: (result: ExecutionResult) => void
  onContinue?: () => void
}

interface LogEntry {
  type: AnsibleLogType | 'info' | 'warning'
  message: string
  task?: string
  task_name?: string
  task_number?: number
}

interface TaskSummary {
  totalTasks: number
  completedTasks: number
  failedTasks: number
  ok: number
  changed: number
  failed: number
}

interface ExecutionResult {
  status: 'success' | 'error' | 'failed' | 'cancelled'
  message?: string
  duration?: number
}

type ExecutionStatus = 'pending' | 'running' | 'success' | 'error' | 'cancelled' | 'failed'

export interface PlaybookExecutorHandle {
  startExecution: (wsPath?: string) => void
  completeExecution: (result: ExecutionResult) => void
  cancelExecution: () => void
}

export const PlaybookExecutor = forwardRef<PlaybookExecutorHandle, PlaybookExecutorProps>(function PlaybookExecutor({
  title,
  websocketPath,
  deploymentId,
  successMessage,
  onRetry,
  onComplete,
  onContinue,
}, ref) {
  // State
  const [isExecuting, setIsExecuting] = useState(false)
  const [showResult, setShowResult] = useState(false)
  const [status, setStatus] = useState<ExecutionStatus>('pending')
  const [message, setMessage] = useState('')
  const [currentTask, setCurrentTask] = useState('')
  const [taskCount, setTaskCount] = useState(0)
  const [duration, setDuration] = useState<number | null>(null)
  const [isCancelling, setIsCancelling] = useState(false)
  const [logOutput, setLogOutput] = useState<LogEntry[]>([])
  const [autoScroll, setAutoScroll] = useState(true)
  const [copySuccess, setCopySuccess] = useState(false)
  const [taskSummary, setTaskSummary] = useState<TaskSummary>({
    totalTasks: 0,
    completedTasks: 0,
    failedTasks: 0,
    ok: 0,
    changed: 0,
    failed: 0,
  })

  // Refs
  const logContainerRef = useRef<HTMLDivElement>(null)
  const websocketRef = useRef<WebSocket | null>(null)
  const startTimeRef = useRef<number>(0)
  const seenTasksRef = useRef<Set<string>>(new Set())

  // WebSocket count tracking (for API service)
  const incrementWebSocketCount = () => {
    // This should be imported from an API utility service when it exists
    // For now, this is a placeholder
  }

  const decrementWebSocketCount = () => {
    // This should be imported from an API utility service when it exists
    // For now, this is a placeholder
  }

  // Auto-scroll effect
  useEffect(() => {
    if (autoScroll && logContainerRef.current) {
      logContainerRef.current.scrollTop = logContainerRef.current.scrollHeight
    }
  }, [logOutput, autoScroll])

  // WebSocket message handler
  const handleWebSocketMessage = useCallback((data: any) => {
    // Add to log
    const newEntry: LogEntry = {
      type: data.type,
      message: data.message,
      task: data.task,
      task_name: data.task_name,
      task_number: data.task_number,
    }
    setLogOutput(prev => [...prev, newEntry])

    // Handle different message types
    switch (data.type) {
      case 'start':
        setCurrentTask('Starting execution...')
        break

      case 'task':
        setCurrentTask(data.task_name || data.message)
        setTaskCount(data.task_number || (prev => prev + 1))

        // Track unique tasks only
        if (data.task_name && !seenTasksRef.current.has(data.task_name)) {
          seenTasksRef.current.add(data.task_name)
          setTaskSummary(prev => ({
            ...prev,
            totalTasks: prev.totalTasks + 1,
          }))
        }
        break

      case 'ok':
      case 'changed':
        // Mark task as completed
        if (data.task && !seenTasksRef.current.has(data.task + '_completed')) {
          seenTasksRef.current.add(data.task + '_completed')
          setTaskSummary(prev => ({
            ...prev,
            completedTasks: prev.completedTasks + 1,
            [data.type]: prev[data.type as 'ok' | 'changed'] + 1,
          }))
        } else {
          setTaskSummary(prev => ({
            ...prev,
            [data.type]: prev[data.type as 'ok' | 'changed'] + 1,
          }))
        }
        break

      case 'failed':
        // Mark task as failed
        if (data.task && !seenTasksRef.current.has(data.task + '_failed')) {
          seenTasksRef.current.add(data.task + '_failed')
          setTaskSummary(prev => ({
            ...prev,
            failedTasks: prev.failedTasks + 1,
            failed: prev.failed + 1,
          }))
        } else {
          setTaskSummary(prev => ({
            ...prev,
            failed: prev.failed + 1,
          }))
        }
        break

      case 'complete':
        const executionDuration = (Date.now() - startTimeRef.current) / 1000
        setDuration(executionDuration)
        setStatus(data.status)
        setMessage(data.message)
        completeExecution({
          status: data.status,
          message: data.message,
          duration: executionDuration,
        })
        break

      case 'error':
        setStatus('error')
        setMessage(data.message)
        break
    }
  }, [])

  // Connect WebSocket
  const connectWebSocket = useCallback((path: string) => {
    const wsProtocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:'
    const wsUrl = `${wsProtocol}//${window.location.host}${path}`
    console.log('Connecting to WebSocket URL:', wsUrl)

    try {
      const ws = new WebSocket(wsUrl)
      websocketRef.current = ws

      ws.onopen = () => {
        console.log('WebSocket connected')
        incrementWebSocketCount()
        setLogOutput(prev => [
          ...prev,
          {
            type: 'info',
            message: 'Connected to execution service',
          },
        ])
      }

      ws.onmessage = (event) => {
        const data = JSON.parse(event.data)
        handleWebSocketMessage(data)
      }

      ws.onerror = (error) => {
        console.error('WebSocket error:', error)
        setLogOutput(prev => [
          ...prev,
          {
            type: 'error',
            message: 'Connection error occurred',
          },
        ])
      }

      ws.onclose = () => {
        console.log('WebSocket disconnected')
        decrementWebSocketCount()
        if (status === 'running') {
          setStatus('error')
          setMessage('Connection lost')
          completeExecution({
            status: 'error',
            message: 'Connection to server lost',
          })
        }
      }
    } catch (error) {
      console.error('Error creating WebSocket:', error)
      setLogOutput(prev => [
        ...prev,
        {
          type: 'error',
          message: `Failed to connect: ${error}`,
        },
      ])
      completeExecution({
        status: 'error',
        message: 'Failed to establish connection',
      })
    }
  }, [handleWebSocketMessage, status])

  // Start execution
  const startExecution = useCallback(
    (wsPath?: string) => {
      setIsExecuting(true)
      setShowResult(false)
      setStatus('running')
      setMessage('')
      setCurrentTask('Connecting...')
      setTaskCount(0)
      setDuration(null)
      setIsCancelling(false)
      setLogOutput([])
      setTaskSummary({
        totalTasks: 0,
        completedTasks: 0,
        failedTasks: 0,
        ok: 0,
        changed: 0,
        failed: 0,
      })
      seenTasksRef.current = new Set()
      startTimeRef.current = Date.now()

      // Connect WebSocket
      const path = wsPath || websocketPath
      if (path) {
        connectWebSocket(path)
      } else if (deploymentId) {
        const deploymentPath = `/api/v1/ws/deployment/${deploymentId}`
        connectWebSocket(deploymentPath)
      }
    },
    [websocketPath, deploymentId, connectWebSocket]
  )

  // Complete execution
  const completeExecution = useCallback(
    (result: ExecutionResult) => {
      websocketRef.current?.close()
      websocketRef.current = null

      // On error, keep the execution modal open for log review
      if (result.status === 'error' || result.status === 'failed') {
        setStatus(result.status)
      } else {
        // On success, show the result modal
        setIsExecuting(false)
        setShowResult(true)
      }

      // Emit completion event
      onComplete?.(result)
    },
    [onComplete]
  )

  // Cancel execution
  const cancelExecution = useCallback(() => {
    setIsCancelling(true)
    websocketRef.current?.close()
    setStatus('cancelled')
    setMessage('Execution was cancelled')
    setIsExecuting(false)
    setShowResult(true)
    setIsCancelling(false)

    const result: ExecutionResult = {
      status: 'cancelled',
      message: 'Execution was cancelled by user',
      duration: duration || undefined,
    }
    onComplete?.(result)
  }, [duration, onComplete])

  // Close executor (on error)
  const closeExecutor = useCallback(() => {
    setIsExecuting(false)
    setShowResult(false)
    setStatus('pending')
    setLogOutput([])
    setTaskSummary({
      totalTasks: 0,
      completedTasks: 0,
      failedTasks: 0,
      ok: 0,
      changed: 0,
      failed: 0,
    })
    setCurrentTask('')
    setMessage('')
    setTaskCount(0)
    setDuration(null)
    seenTasksRef.current.clear()
  }, [])

  // Close result modal
  const closeResult = useCallback(() => {
    setShowResult(false)

    // Only emit continue if the playbook was successful
    if (status === 'success') {
      onContinue?.()
    }

    // Reset state
    setStatus('pending')
    setMessage('')
    setCurrentTask('')
    setTaskCount(0)
    setDuration(null)
    setLogOutput([])
    setTaskSummary({
      totalTasks: 0,
      completedTasks: 0,
      failedTasks: 0,
      ok: 0,
      changed: 0,
      failed: 0,
    })
    seenTasksRef.current = new Set()
  }, [status, onContinue])

  // Retry execution
  const retry = useCallback(() => {
    if (onRetry) {
      setShowResult(false)
      setStatus('pending')
      setMessage('')
      setCurrentTask('')
      setTaskCount(0)
      setDuration(null)
      setLogOutput([])
      setTaskSummary({
        totalTasks: 0,
        completedTasks: 0,
        failedTasks: 0,
        ok: 0,
        changed: 0,
        failed: 0,
      })
      onRetry()
    }
  }, [onRetry])

  // Copy output to clipboard
  const copyOutput = useCallback(async () => {
    try {
      const header = `${title} - Execution Log
=====================================
Status: ${status}
Duration: ${duration ? formatDuration(duration) : 'N/A'}
Tasks: Total ${taskSummary.totalTasks}, Completed ${taskSummary.completedTasks}, Failed ${taskSummary.failedTasks}
Timestamp: ${new Date().toISOString()}
=====================================

`
      const logText = logOutput.map((log) => log.message).join('\n')
      const fullText = header + logText

      await navigator.clipboard.writeText(fullText)
      setCopySuccess(true)
      setTimeout(() => setCopySuccess(false), 2000)
    } catch (err) {
      console.error('Failed to copy output:', err)
      alert('Failed to copy output to clipboard')
    }
  }, [title, status, duration, taskSummary, logOutput])

  // Format duration helper
  const formatDuration = (seconds: number): string => {
    if (seconds < 60) {
      return `${seconds.toFixed(1)} seconds`
    } else {
      const minutes = Math.floor(seconds / 60)
      const remainingSeconds = Math.floor(seconds % 60)
      return `${minutes}m ${remainingSeconds}s`
    }
  }

  // Format log message (escape HTML and replace \n)
  const formatLogMessage = (message: string): string => {
    const div = document.createElement('div')
    div.textContent = message
    const escaped = div.innerHTML
    return escaped.replace(/\\n/g, '<br>')
  }

  // Expose methods via ref (for parent components)
  useImperativeHandle(ref, () => ({
    startExecution,
    completeExecution,
    cancelExecution,
  }), [startExecution, completeExecution, cancelExecution])

  return (
    <>
      {/* Progress Modal */}
      <TkDialogRoot open={isExecuting} onOpenChange={(open) => {
        // Prevent closing during running deployment - force use of Cancel button
        if (!open && status === 'running') return
        if (!open) closeExecutor()
      }}>
        <TkDialogContent className="max-w-3xl max-h-[90vh]">
          <TkDialogHeader>
            <TkDialogTitle>{title}</TkDialogTitle>
          </TkDialogHeader>

          <div className="flex flex-col gap-4"> {/* @allowed-inline */}
            {/* Task Progress */}
            {currentTask && (
              <div>
                <div className="flex justify-between text-sm mb-1"> {/* @allowed-inline */}
                  <span className="font-semibold">{currentTask}</span>
                  {taskCount > 0 && (
                    <span className="text-sm text-muted-foreground">Task {taskCount}</span>
                  )}
                </div>
              </div>
            )}

            {/* Live Output Log */}
            <div>
              <div className="flex justify-between items-center mb-2"> {/* @allowed-inline */}
                <span className="text-sm text-muted-foreground">Live Output:</span>
                <div className="flex items-center gap-2"> {/* @allowed-inline */}
                  <TkButton
                    variant="ghost"
                    size="sm"
                    onClick={copyOutput}
                    className={copySuccess ? 'text-success' : ''}
                  >
                    {copySuccess ? (
                      <>
                        <Check className="w-4 h-4 mr-1" />
                        Copied!
                      </>
                    ) : (
                      <>
                        <Copy className="w-4 h-4 mr-1" />
                        Copy
                      </>
                    )}
                  </TkButton>
                  <div className="flex items-center gap-2"> {/* @allowed-inline */}
                    <TkLabel htmlFor="auto-scroll" className="text-xs cursor-pointer">
                      Auto-scroll
                    </TkLabel>
                    <TkSwitch
                      id="auto-scroll"
                      checked={autoScroll}
                      onCheckedChange={setAutoScroll}
                    />
                  </div>
                </div>
              </div>
              <div
                ref={logContainerRef}
                className="h-96 overflow-y-auto overflow-x-hidden p-4 bg-muted/30 rounded-lg font-mono text-sm" /* @allowed-inline */
              >
                {logOutput.length === 0 ? (
                  <div className="text-muted-foreground">
                    <span className="text-muted-foreground">$ </span>
                    Waiting for output...
                  </div>
                ) : (
                  logOutput.map((log, idx) => (
                    <div key={idx} className={`${getAnsibleLogClassName(log.type as AnsibleLogType)} whitespace-pre-wrap break-all`}>
                      <span className="text-muted-foreground">
                        {getAnsibleLogPrefix(log.type as AnsibleLogType)}{' '}
                      </span>
                      <span dangerouslySetInnerHTML={{ __html: formatLogMessage(log.message) }} />
                    </div>
                  ))
                )}
              </div>
            </div>

            {/* Status Summary */}
            {taskSummary.totalTasks > 0 && (
              <div className="grid grid-cols-4 gap-4"> {/* @allowed-inline */}
                <TkCard>
                  <TkCardContent className="text-center py-2"> {/* @allowed-inline */}
                    <div className="text-xs text-muted-foreground">Tasks</div>
                    <div className="text-lg font-bold">{taskSummary.totalTasks}</div>
                  </TkCardContent>
                </TkCard>
                <TkCard>
                  <TkCardContent className="text-center py-2"> {/* @allowed-inline */}
                    <div className="text-xs text-muted-foreground">OK</div>
                    <div className="text-lg font-bold text-success">{taskSummary.ok}</div>
                  </TkCardContent>
                </TkCard>
                <TkCard>
                  <TkCardContent className="text-center py-2"> {/* @allowed-inline */}
                    <div className="text-xs text-muted-foreground">Changed</div>
                    <div className="text-lg font-bold text-warning">{taskSummary.changed}</div>
                  </TkCardContent>
                </TkCard>
                {taskSummary.failed > 0 && (
                  <TkCard>
                    <TkCardContent className="text-center py-2"> {/* @allowed-inline */}
                      <div className="text-xs text-muted-foreground">Failed</div>
                      <div className="text-lg font-bold text-destructive">{taskSummary.failed}</div>
                    </TkCardContent>
                  </TkCard>
                )}
              </div>
            )}
          </div>

          {/* Action Buttons */}
          <TkDialogFooter>
            {status === 'running' && (
              <TkButton variant="outline" size="sm" onClick={cancelExecution} disabled={isCancelling}>
                {isCancelling && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                {isCancelling ? 'Cancelling...' : 'Cancel'}
              </TkButton>
            )}
            {(status === 'error' || status === 'failed') && (
              <TkButton size="sm" onClick={closeExecutor}>
                Close
              </TkButton>
            )}
          </TkDialogFooter>
        </TkDialogContent>
      </TkDialogRoot>

      {/* Result Modal */}
      <TkDialogRoot open={showResult} onOpenChange={(open) => !open && closeResult()}>
        <TkDialogContent className="max-w-2xl">
          <TkDialogHeader>
            <TkDialogTitle>{title} - Complete</TkDialogTitle>
          </TkDialogHeader>

          <div className="flex flex-col gap-4"> {/* @allowed-inline */}
            {/* Success Result */}
            {status === 'success' && (
              <TkSuccessAlert>
                {message || successMessage || 'Playbook completed successfully'}
              </TkSuccessAlert>
            )}

            {/* Error Result */}
            {status === 'error' && (
              <>
                <TkErrorAlert>
                  {message || 'Playbook execution failed'}
                </TkErrorAlert>

                {/* GitHub Issue Helper */}
                <TkInfoAlert title="Need help?">
                  <p className="text-sm">
                    Copy the log output and create an issue on GitHub for assistance.
                  </p>
                </TkInfoAlert>
              </>
            )}

            {/* Final Summary */}
            {taskSummary.totalTasks > 0 && (
              <div>
                <p className="text-sm text-muted-foreground mb-2">Execution Summary:</p>
                <div className="text-sm">
                  <p>Total Tasks: {taskSummary.totalTasks}</p>
                  <p className="text-success">Completed: {taskSummary.completedTasks}</p>
                  {taskSummary.failedTasks > 0 && (
                    <p className="text-destructive">Failed: {taskSummary.failedTasks}</p>
                  )}
                </div>
              </div>
            )}

            {/* Execution Time */}
            {duration && (
              <div className="text-sm text-muted-foreground">
                Completed in {formatDuration(duration)}
              </div>
            )}
          </div>

          {/* Actions */}
          <TkDialogFooter>
            <TkButton
              variant="ghost"
              size="sm"
              onClick={copyOutput}
              className={copySuccess ? 'text-success' : ''}
            >
              {copySuccess ? (
                <>
                  <Check className="w-4 h-4 mr-1" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4 mr-1" />
                  Copy Log
                </>
              )}
            </TkButton>
            <TkButton size="sm" onClick={closeResult}>
              {status === 'success' ? 'Continue' : 'Close'}
            </TkButton>
            {status === 'error' && onRetry && (
              <TkButton variant="outline" size="sm" onClick={retry}>
                Retry
              </TkButton>
            )}
          </TkDialogFooter>
        </TkDialogContent>
      </TkDialogRoot>
    </>
  )
})

// frontend/src/components/PlaybookExecutor.vue
<!-- src/components/PlaybookExecutor.vue -->
<template>
  <div class="playbook-executor">
    <!-- Progress Modal -->
    <dialog class="modal" :open="isExecuting">
      <div class="modal-box max-w-3xl max-h-[90vh]">
        <h3 class="font-bold text-lg mb-4">{{ title }}</h3>
        
        <!-- Task Progress -->
        <div v-if="currentTask" class="mb-4">
          <div class="flex justify-between text-sm mb-1">
            <span class="font-semibold">{{ currentTask }}</span>
            <span v-if="taskCount > 0" class="text-sm text-base-content text-opacity-70">
              Task {{ taskCount }}
            </span>
          </div>
        </div>
        
        <!-- Live Output Log -->
        <div class="mb-4">
          <div class="flex justify-between items-center mb-2">
            <span class="text-sm text-gray-600">Live Output:</span>
            <div class="flex items-center gap-2">
              <button 
                class="btn btn-ghost btn-xs gap-1"
                @click="copyOutput"
                :class="{ 'btn-success': copySuccess }"
              >
                <svg v-if="!copySuccess" class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3"></path>
                </svg>
                <svg v-else class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                </svg>
                {{ copySuccess ? 'Copied!' : 'Copy' }}
              </button>
              <label class="label cursor-pointer gap-2">
                <span class="label-text text-xs">Auto-scroll</span>
                <input type="checkbox" v-model="autoScroll" class="checkbox checkbox-xs" />
              </label>
            </div>
          </div>
          <div 
            class="mockup-code h-96 overflow-y-auto text-xs"
            ref="logContainer"
          >
            <div v-if="logOutput.length === 0" class="text-base-content text-opacity-50">
              <pre data-prefix="$"><code>Waiting for output...</code></pre>
            </div>
            <pre
              v-for="(log, idx) in logOutput"
              :key="idx"
              :data-prefix="getLogPrefix(log.type)"
              :class="getLogClass(log.type)"
            ><code v-html="formatLogMessage(log.message)"></code></pre>
          </div>
        </div>
        
        <!-- Status Summary -->
        <div v-if="taskSummary.totalTasks > 0" class="stats stats-horizontal w-full mb-4">
          <div class="stat place-items-center py-2">
            <div class="stat-title text-xs">Tasks</div>
            <div class="stat-value text-lg">{{ taskSummary.totalTasks }}</div>
          </div>
          <div class="stat place-items-center py-2">
            <div class="stat-title text-xs">OK</div>
            <div class="stat-value text-lg text-success">{{ taskSummary.ok }}</div>
          </div>
          <div class="stat place-items-center py-2">
            <div class="stat-title text-xs">Changed</div>
            <div class="stat-value text-lg text-warning">{{ taskSummary.changed }}</div>
          </div>
          <div v-if="taskSummary.failed > 0" class="stat place-items-center py-2">
            <div class="stat-title text-xs">Failed</div>
            <div class="stat-value text-lg text-error">{{ taskSummary.failed }}</div>
          </div>
        </div>

        <!-- Action Buttons -->
        <div class="modal-footer">
          <!-- Cancel Button (during execution) -->
          <button v-if="status === 'running'" class="btn btn-outline btn-sm" @click="cancelExecution" :disabled="isCancelling">
            <span v-if="isCancelling" class="loading loading-spinner loading-xs"></span>
            {{ isCancelling ? 'Cancelling...' : 'Cancel' }}
          </button>

          <!-- Close Button (on error) -->
          <button v-if="status === 'error' || status === 'failed'" class="btn btn-sm" @click="closeExecutor">
            Close
          </button>
        </div>
      </div>
    </dialog>

    <!-- Result Modal -->
    <dialog class="modal" :open="showResult">
      <div class="modal-box max-w-2xl">
        <h3 class="font-bold text-lg mb-4">{{ title }} - Complete</h3>
        
        <!-- Success Result -->
        <div v-if="status === 'success'" class="alert alert-success mb-4">
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span>{{ message || successMessage || 'Playbook completed successfully' }}</span>
        </div>
        
        <!-- Error Result -->
        <div v-if="status === 'error'">
          <div class="alert alert-error mb-4">
            <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <span>{{ message || 'Playbook execution failed' }}</span>
          </div>
          
          <!-- GitHub Issue Helper -->
          <div class="alert alert-info mb-4">
            <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
            </svg>
            <div>
              <p class="font-semibold">Need help?</p>
              <p class="text-sm">Copy the log output and create an issue on GitHub for assistance.</p>
            </div>
          </div>
        </div>
        
        <!-- Final Summary -->
        <div v-if="taskSummary.totalTasks > 0" class="mb-4">
          <p class="text-sm text-gray-600 mb-2">Execution Summary:</p>
          <div class="text-sm">
            <p>Total Tasks: {{ taskSummary.totalTasks }}</p>
            <p class="text-success">Completed: {{ taskSummary.completedTasks }}</p>
            <p v-if="taskSummary.failedTasks > 0" class="text-error">Failed: {{ taskSummary.failedTasks }}</p>
          </div>
        </div>
        
        <!-- Execution Time -->
        <div v-if="duration" class="mb-4">
          <div class="text-sm text-gray-600">
            Completed in {{ formatDuration(duration) }}
          </div>
        </div>

        <!-- Actions -->
        <div class="modal-footer">
          <button
            class="btn btn-ghost btn-sm gap-1"
            @click="copyOutput"
            :class="{ 'btn-success': copySuccess }"
          >
            <svg v-if="!copySuccess" class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3"></path>
            </svg>
            <svg v-else class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
            </svg>
            {{ copySuccess ? 'Copied!' : 'Copy Log' }}
          </button>
          <button class="btn btn-primary btn-sm" @click="closeResult">
            {{ status === 'success' ? 'Continue' : 'Close' }}
          </button>
          <button v-if="status === 'error' && onRetry" class="btn btn-outline btn-sm" @click="retry">
            Retry
          </button>
        </div>
      </div>
      <div class="modal-backdrop" @click="closeResult"></div>
    </dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, nextTick } from 'vue'
import { incrementWebSocketCount, decrementWebSocketCount } from '@/services/api'

interface PlaybookExecutorProps {
  title: string
  websocketPath?: string  // For direct WebSocket connection
  deploymentId?: string  // For deployment monitoring
  successMessage?: string  // Custom success message
  onRetry?: () => void
  onComplete?: (result: any) => void
}

interface LogEntry {
  type: 'start' | 'play' | 'task' | 'ok' | 'changed' | 'failed' | 'skipped' | 'output' | 'error' | 'complete' | 'info' | 'warning'
  message: string
  task?: string
  task_name?: string
  task_number?: number
}

const props = defineProps<PlaybookExecutorProps>()

const emit = defineEmits(['complete', 'continue'])

// Reactive state
const isExecuting = ref(false)
const showResult = ref(false)
const status = ref<'pending' | 'running' | 'success' | 'error' | 'cancelled'>('pending')
const message = ref('')
const currentTask = ref('')
const taskCount = ref(0)
const duration = ref<number | null>(null)
const isCancelling = ref(false)
const logOutput = ref<LogEntry[]>([])
const logContainer = ref<HTMLElement>()
const autoScroll = ref(true)
const websocket = ref<WebSocket | null>(null)
const startTime = ref<number>(0)
const copySuccess = ref(false)

// Task summary - track unique tasks rather than host executions
const taskSummary = ref({
  totalTasks: 0,
  completedTasks: 0,
  failedTasks: 0,
  ok: 0,
  changed: 0,
  failed: 0
})
const seenTasks = ref(new Set())

// Methods
const startExecution = (wsPath?: string) => {
  isExecuting.value = true
  showResult.value = false
  status.value = 'running'
  message.value = ''
  currentTask.value = 'Connecting...'
  taskCount.value = 0
  duration.value = null
  isCancelling.value = false
  logOutput.value = []
  taskSummary.value = { totalTasks: 0, completedTasks: 0, failedTasks: 0, ok: 0, changed: 0, failed: 0 }
  seenTasks.value = new Set()
  startTime.value = Date.now()
  
  // Connect WebSocket
  const path = wsPath || props.websocketPath
  if (path) {
    connectWebSocket(path)
  } else if (props.deploymentId) {
    connectDeploymentWebSocket(props.deploymentId)
  }
}

const connectWebSocket = (path: string) => {
  const wsProtocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:'
  const wsUrl = `${wsProtocol}//${window.location.host}${path}`
  console.log('Connecting to WebSocket URL:', wsUrl)
  
  try {
    websocket.value = new WebSocket(wsUrl)
    
    websocket.value.onopen = () => {
      console.log('WebSocket connected')
      incrementWebSocketCount()
      logOutput.value.push({
        type: 'info',
        message: 'Connected to execution service'
      })
    }
    
    websocket.value.onmessage = (event) => {
      const data = JSON.parse(event.data)
      handleWebSocketMessage(data)
    }
    
    websocket.value.onerror = (error) => {
      console.error('WebSocket error:', error)
      logOutput.value.push({
        type: 'error',
        message: 'Connection error occurred'
      })
    }
    
    websocket.value.onclose = () => {
      console.log('WebSocket disconnected')
      decrementWebSocketCount()
      if (status.value === 'running') {
        status.value = 'error'
        message.value = 'Connection lost'
        completeExecution({
          status: 'error',
          message: 'Connection to server lost'
        })
      }
    }
  } catch (error) {
    console.error('Error creating WebSocket:', error)
    logOutput.value.push({
      type: 'error',
      message: `Failed to connect: ${error}`
    })
    completeExecution({
      status: 'error',
      message: 'Failed to establish connection'
    })
  }
}

const connectDeploymentWebSocket = (deploymentId: string) => {
  const wsProtocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:'
  const wsUrl = `${wsProtocol}//${window.location.host}/api/v1/ws/deployment/${deploymentId}`
  connectWebSocket(wsUrl)
}

const handleWebSocketMessage = (data: any) => {
  // Add to log
  logOutput.value.push({
    type: data.type,
    message: data.message,
    task: data.task,
    task_name: data.task_name,
    task_number: data.task_number
  })
  
  // Auto-scroll to bottom
  if (autoScroll.value) {
    nextTick(() => {
      if (logContainer.value) {
        logContainer.value.scrollTop = logContainer.value.scrollHeight
      }
    })
  }
  
  // Handle different message types
  switch (data.type) {
    case 'start':
      currentTask.value = 'Starting execution...'
      break
      
    case 'task':
      currentTask.value = data.task_name || data.message
      taskCount.value = data.task_number || taskCount.value + 1
      
      // Track unique tasks only
      if (data.task_name && !seenTasks.value.has(data.task_name)) {
        seenTasks.value.add(data.task_name)
        taskSummary.value.totalTasks++
      }
      break
      
    case 'ok':
    case 'changed':
      // Mark task as completed (count unique tasks, not individual host results)
      if (data.task && !seenTasks.value.has(data.task + '_completed')) {
        seenTasks.value.add(data.task + '_completed')
        taskSummary.value.completedTasks++
      }
      if (data.type === 'ok') taskSummary.value.ok++
      if (data.type === 'changed') taskSummary.value.changed++
      break
      
    case 'failed':
      // Mark task as failed
      if (data.task && !seenTasks.value.has(data.task + '_failed')) {
        seenTasks.value.add(data.task + '_failed')
        taskSummary.value.failedTasks++
      }
      taskSummary.value.failed++
      break
      
    case 'complete':
      duration.value = (Date.now() - startTime.value) / 1000
      status.value = data.status
      message.value = data.message
      completeExecution({
        status: data.status,
        message: data.message,
        duration: duration.value
      })
      break
      
    case 'error':
      status.value = 'error'
      message.value = data.message
      break
  }
}

const completeExecution = (result: any) => {
  websocket.value?.close()
  websocket.value = null

  // On error, keep the execution modal open for log review
  if (result.status === 'error' || result.status === 'failed') {
    // Don't close the modal or show result modal on error
    // User can still see logs and must manually close
    status.value = result.status
  } else {
    // On success, show the result modal
    isExecuting.value = false
    showResult.value = true
  }

  // Emit completion event
  emit('complete', result)

  // Call onComplete prop if provided
  if (props.onComplete) {
    props.onComplete(result)
  }

  // No auto-continue - user must manually close the modal
  // This allows them to read the logs, especially on error
}

const cancelExecution = () => {
  isCancelling.value = true
  websocket.value?.close()
  status.value = 'cancelled'
  message.value = 'Execution was cancelled'
  isExecuting.value = false
  showResult.value = true
  isCancelling.value = false
  
  // Emit completion event with cancelled status
  const result = {
    status: 'cancelled',
    message: 'Execution was cancelled by user',
    duration: duration.value
  }
  emit('complete', result)
  
  // Call onComplete prop if provided
  if (props.onComplete) {
    props.onComplete(result)
  }
}

const closeExecutor = () => {
  // Reset all state
  isExecuting.value = false
  showResult.value = false
  status.value = 'pending'
  logOutput.value = []
  taskSummary.value = { totalTasks: 0, completedTasks: 0, failedTasks: 0, ok: 0, changed: 0, failed: 0 }
  currentTask.value = ''
  message.value = ''
  taskCount.value = 0
  duration.value = null
  seenTasks.value.clear()
}

const closeResult = () => {
  showResult.value = false

  // Only emit continue if the playbook was successful
  if (status.value === 'success') {
    emit('continue')
  }

  // Reset state
  status.value = 'pending'
  message.value = ''
  currentTask.value = ''
  taskCount.value = 0
  duration.value = null
  logOutput.value = []
  taskSummary.value = { totalTasks: 0, completedTasks: 0, failedTasks: 0, ok: 0, changed: 0, failed: 0 }
  seenTasks.value = new Set()
}

const retry = () => {
  if (props.onRetry) {
    // Close the result modal without emitting continue
    showResult.value = false
    
    // Reset state
    status.value = 'pending'
    message.value = ''
    currentTask.value = ''
    taskCount.value = 0
    duration.value = null
    logOutput.value = []
    taskSummary.value = { total: 0, ok: 0, changed: 0, failed: 0, skipped: 0 }
    
    // Call the retry handler
    props.onRetry()
  }
}

const copyOutput = async () => {
  try {
    // Build the output text with metadata
    const header = `${props.title} - Execution Log
=====================================
Status: ${status.value}
Duration: ${duration.value ? formatDuration(duration.value) : 'N/A'}
Tasks: Total ${taskSummary.value.totalTasks}, Completed ${taskSummary.value.completedTasks}, Failed ${taskSummary.value.failedTasks}
Timestamp: ${new Date().toISOString()}
=====================================

`
    
    // Combine all log messages
    const logText = logOutput.value
      .map(log => log.message)
      .join('\n')
    
    const fullText = header + logText
    
    // Copy to clipboard
    await navigator.clipboard.writeText(fullText)
    
    // Show success feedback
    copySuccess.value = true
    setTimeout(() => {
      copySuccess.value = false
    }, 2000)
  } catch (err) {
    console.error('Failed to copy output:', err)
    alert('Failed to copy output to clipboard')
  }
}

const formatDuration = (seconds: number): string => {
  if (seconds < 60) {
    return `${seconds.toFixed(1)} seconds`
  } else {
    const minutes = Math.floor(seconds / 60)
    const remainingSeconds = Math.floor(seconds % 60)
    return `${minutes}m ${remainingSeconds}s`
  }
}

const getLogClass = (type: string): string => {
  switch (type) {
    case 'task':
      return 'text-info font-semibold'
    case 'play':
      return 'text-primary font-semibold'
    case 'ok':
      return 'text-success'
    case 'changed':
      return 'text-warning'
    case 'failed':
      return 'text-error'
    case 'error':
      return 'text-error font-semibold'
    case 'skipped':
      return 'text-base-content text-opacity-50'
    case 'warning':
      return 'text-warning font-semibold'
    case 'start':
    case 'complete':
      return 'text-accent font-semibold'
    default:
      return 'text-base-content'
  }
}

const formatLogMessage = (message: string): string => {
  // Escape HTML to prevent XSS
  const escapeHtml = (text: string): string => {
    const div = document.createElement('div')
    div.textContent = text
    return div.innerHTML
  }

  // Escape HTML first, then replace literal \n with <br> tags
  const escaped = escapeHtml(message)
  return escaped.replace(/\\n/g, '<br>')
}

const getLogPrefix = (type: string): string => {
  switch (type) {
    case 'task':
      return '>'
    case 'play':
      return '#'
    case 'ok':
      return '✓'
    case 'changed':
      return '~'
    case 'failed':
      return '✗'
    case 'error':
      return '!'
    case 'skipped':
      return '-'
    case 'warning':
      return '⚠'
    case 'start':
      return '$'
    case 'complete':
      return '>'
    default:
      return ' '
  }
}

// Expose methods to parent component
defineExpose({
  startExecution,
  completeExecution,
  cancelExecution
})
</script>

<style scoped>
/* Custom scrollbar for log container */
.overflow-y-auto::-webkit-scrollbar {
  width: 8px;
}

.overflow-y-auto::-webkit-scrollbar-track {
  background: rgba(0, 0, 0, 0.2);
  border-radius: 4px;
}

.overflow-y-auto::-webkit-scrollbar-thumb {
  background: rgba(255, 255, 255, 0.3);
  border-radius: 4px;
}

.overflow-y-auto::-webkit-scrollbar-thumb:hover {
  background: rgba(255, 255, 255, 0.5);
}

/* Terminal-like appearance */
.mockup-code {
  background-color: #1a1a1a !important;
  color: #e0e0e0 !important;
}

.mockup-code pre {
  color: inherit !important;
  white-space: pre-wrap !important; /* Allow line wrapping */
  word-break: break-word !important; /* Break long words */
}

.mockup-code code {
  color: inherit !important;
  background: transparent !important;
}

/* Ensure prefix symbols are visible */
.mockup-code pre::before {
  color: #666 !important;
}

/* Adjust semantic colors for dark background */
.mockup-code .text-info {
  color: #60a5fa !important; /* Bright blue */
}

.mockup-code .text-success {
  color: #4ade80 !important; /* Bright green */
}

.mockup-code .text-warning {
  color: #fbbf24 !important; /* Bright yellow */
}

.mockup-code .text-error {
  color: #f87171 !important; /* Bright red */
}

.mockup-code .text-primary {
  color: #38bdf8 !important; /* Bright cyan */
}

.mockup-code .text-accent {
  color: #fb923c !important; /* Bright orange */
}

.mockup-code .text-secondary {
  color: #a1a1aa !important; /* Light gray */
}

.mockup-code .text-base-content {
  color: #e0e0e0 !important; /* Light gray for regular text */
}
</style>
