// frontend/src/views/ImageMirrorDeployment.vue
<template>
  <div class="container mx-auto px-4 py-8">
    <h1 class="font-bold mb-6">Image Mirror Deployment</h1>

    <div class="card bg-base-100 shadow-xl">
      <div class="card-body">
        <h2 class="card-title">{{ deploymentName }}</h2>

        <div v-if="deployment" class="mb-4">
          <div class="flex items-center gap-4">
            <span class="text-sm">Status:</span>
            <span class="badge" :class="statusBadgeClass">{{ deployment.status }}</span>
          </div>
          <div v-if="deployment.variables" class="mt-2 text-sm">
            <div>Source: {{ deployment.variables.source_image }}</div>
            <div>Description: {{ deployment.variables.image_description || '-' }}</div>
          </div>
        </div>

        <!-- Playbook Executor for WebSocket streaming -->
        <PlaybookExecutor
          ref="playbookExecutor"
          :title="`Mirroring: ${deploymentName}`"
          @complete="onDeploymentComplete"
        />

        <div v-if="deploymentComplete" class="mt-6">
          <div class="alert" :class="deploymentSuccess ? 'alert-success' : 'alert-error'">
            <div>
              <svg v-if="deploymentSuccess" xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              <svg v-else xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              <span>{{ deploymentMessage }}</span>
            </div>
          </div>

          <div class="card-actions justify-end mt-4">
            <button @click="goToImages" class="btn btn-primary">
              Back to Images
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import PlaybookExecutor from '@/components/PlaybookExecutor.vue'
import { api } from '@/services/api'

const route = useRoute()
const router = useRouter()

const deploymentId = computed(() => route.params.deploymentId)
const deployment = ref(null)
const deploymentName = ref('Image Mirror')
const playbookExecutor = ref(null)
const deploymentComplete = ref(false)
const deploymentSuccess = ref(false)
const deploymentMessage = ref('')

const statusBadgeClass = computed(() => {
  if (!deployment.value) return 'badge-ghost'
  switch (deployment.value.status) {
    case 'success': return 'badge-success'
    case 'failed': return 'badge-error'
    case 'running': return 'badge-warning'
    case 'pending': return 'badge-info'
    default: return 'badge-ghost'
  }
})

onMounted(async () => {
  if (!deploymentId.value) {
    console.error('No deployment ID provided')
    router.push('/harbor-images')
    return
  }

  try {
    // Get deployment details
    const response = await api.get(`/templates/deployments/${deploymentId.value}`)
    deployment.value = response.data

    if (deployment.value.variables?.source_image) {
      const source = deployment.value.variables.source_image
      const imageName = source.split('/').pop().split(':')[0]
      deploymentName.value = `Mirror: ${imageName}`
    }

    // Start WebSocket connection if deployment is pending or running
    if (deployment.value.status === 'pending' || deployment.value.status === 'running') {
      const wsUrl = `/api/v1/ws/harbor/mirror/${deploymentId.value}`
      playbookExecutor.value?.startExecution(wsUrl)
    } else {
      // Deployment already completed
      deploymentComplete.value = true
      deploymentSuccess.value = deployment.value.status === 'success'
      deploymentMessage.value = deployment.value.status === 'success'
        ? 'Image mirrored successfully!'
        : 'Image mirroring failed'
    }
  } catch (error) {
    console.error('Failed to load deployment:', error)
    alert('Failed to load deployment details')
    router.push('/harbor-images')
  }
})

const onDeploymentComplete = (success) => {
  deploymentComplete.value = true
  deploymentSuccess.value = success
  deploymentMessage.value = success
    ? 'Image mirrored successfully!'
    : 'Image mirroring failed'

  // Reload deployment status
  loadDeploymentStatus()
}

const loadDeploymentStatus = async () => {
  try {
    const response = await api.get(`/templates/deployments/${deploymentId.value}`)
    deployment.value = response.data
  } catch (error) {
    console.error('Failed to reload deployment status:', error)
  }
}

const goToImages = () => {
  router.push('/harbor-images')
}

onUnmounted(() => {
  // Cleanup WebSocket connection if needed
  if (playbookExecutor.value) {
    // PlaybookExecutor should handle its own cleanup
  }
})
</script>

// frontend/src/pages/ImageMirrorDeployment.tsx
'use client'

import { useState, useEffect, useRef } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Loader2 } from 'lucide-react'
import { TkButton } from 'thinkube-style/components/buttons-badges'
import { TkBadge } from 'thinkube-style/components/buttons-badges'
import {
  TkCard,
  TkCardHeader,
  TkCardTitle,
  TkCardContent,
  TkCardFooter,
} from 'thinkube-style/components/cards-data'
import { TkPageWrapper } from 'thinkube-style/components/utilities'
import { TkSuccessAlert, TkErrorAlert } from 'thinkube-style/components/feedback'
import { PlaybookExecutor } from '../components/PlaybookExecutor'
import api from '../lib/axios'

interface DeploymentVariables {
  source_image: string
  image_description?: string
}

interface Deployment {
  id: string
  status: 'pending' | 'running' | 'success' | 'failed'
  variables?: DeploymentVariables
}

interface ExecutionResult {
  status: 'success' | 'error' | 'failed' | 'cancelled'
  message?: string
  duration?: number
}

export function ImageMirrorDeployment() {
  const navigate = useNavigate()
  const { deploymentId } = useParams<{ deploymentId: string }>()

  const [deployment, setDeployment] = useState<Deployment | null>(null)
  const [deploymentName, setDeploymentName] = useState('Image Mirror')
  const [deploymentComplete, setDeploymentComplete] = useState(false)
  const [deploymentSuccess, setDeploymentSuccess] = useState(false)
  const [deploymentMessage, setDeploymentMessage] = useState('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const playbookExecutorRef = useRef<{ startExecution: (wsPath: string) => void } | null>(null)

  // Badge variant mapping
  const getStatusBadgeVariant = (status: string) => {
    switch (status) {
      case 'success':
        return 'success'
      case 'failed':
        return 'destructive'
      case 'running':
        return 'warning'
      case 'pending':
        return 'default'
      default:
        return 'outline'
    }
  }

  useEffect(() => {
    if (!deploymentId) {
      navigate('/harbor-images')
      return
    }

    loadDeployment()
  }, [deploymentId, navigate])

  const loadDeployment = async () => {
    if (!deploymentId) return

    try {
      setLoading(true)
      const response = await api.get(`/templates/deployments/${deploymentId}`)
      const deploymentData: Deployment = response.data
      setDeployment(deploymentData)

      // Set deployment name based on source image
      if (deploymentData.variables?.source_image) {
        const source = deploymentData.variables.source_image
        const imageName = source.split('/').pop()?.split(':')[0] || 'Image'
        setDeploymentName(`Mirror: ${imageName}`)
      }

      // Start WebSocket connection if deployment is pending or running
      if (deploymentData.status === 'pending' || deploymentData.status === 'running') {
        const wsUrl = `/api/v1/ws/harbor/mirror/${deploymentId}`
        // Note: In the actual implementation, we'd need to expose startExecution
        // For now, this demonstrates the pattern
        setTimeout(() => {
          // Simulating the execution start
        }, 100)
      } else {
        // Deployment already completed
        setDeploymentComplete(true)
        setDeploymentSuccess(deploymentData.status === 'success')
        setDeploymentMessage(
          deploymentData.status === 'success'
            ? 'Image mirrored successfully!'
            : 'Image mirroring failed'
        )
      }
    } catch (err) {
      setError('Failed to load deployment details')
      setTimeout(() => navigate('/harbor-images'), 2000)
    } finally {
      setLoading(false)
    }
  }

  const loadDeploymentStatus = async () => {
    if (!deploymentId) return

    try {
      const response = await api.get(`/templates/deployments/${deploymentId}`)
      setDeployment(response.data)
    } catch (err) {
      // Error is silent, status reload is not critical
    }
  }

  const onDeploymentComplete = (result: ExecutionResult) => {
    setDeploymentComplete(true)
    setDeploymentSuccess(result.status === 'success')
    setDeploymentMessage(
      result.status === 'success'
        ? 'Image mirrored successfully!'
        : 'Image mirroring failed'
    )

    // Reload deployment status
    loadDeploymentStatus()
  }

  const goToImages = () => {
    navigate('/harbor-images')
  }

  if (loading) {
    return (
      <TkPageWrapper title="Image Mirror Deployment">
        <TkCard>
          <TkCardContent className="flex items-center justify-center py-12">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
          </TkCardContent>
        </TkCard>
      </TkPageWrapper>
    )
  }

  if (error) {
    return (
      <TkPageWrapper title="Image Mirror Deployment">
        <TkErrorAlert>{error}</TkErrorAlert>
      </TkPageWrapper>
    )
  }

  return (
    <TkPageWrapper title="Image Mirror Deployment">
      <TkCard>
        <TkCardHeader>
          <TkCardTitle>{deploymentName}</TkCardTitle>
        </TkCardHeader>

        <TkCardContent className="space-y-4">
          {deployment && (
            <TkCard variant="outline">
              <TkCardContent className="py-3">
                <span className="text-sm font-medium">Status:</span>
                {' '}
                <TkBadge variant={getStatusBadgeVariant(deployment.status)}>
                  {deployment.status}
                </TkBadge>
                {deployment.variables && (
                  <>
                    <div className="mt-2 text-sm">Source: {deployment.variables.source_image}</div>
                    <div className="text-sm">
                      Description: {deployment.variables.image_description || '-'}
                    </div>
                  </>
                )}
              </TkCardContent>
            </TkCard>
          )}

          {/* Playbook Executor for WebSocket streaming */}
          <PlaybookExecutor
            title={`Mirroring: ${deploymentName}`}
            websocketPath={`/api/v1/ws/harbor/mirror/${deploymentId}`}
            onComplete={onDeploymentComplete}
          />

          {deploymentComplete && (
            <>
              {deploymentSuccess ? (
                <TkSuccessAlert>{deploymentMessage}</TkSuccessAlert>
              ) : (
                <TkErrorAlert>{deploymentMessage}</TkErrorAlert>
              )}
            </>
          )}
        </TkCardContent>

        {deploymentComplete && (
          <TkCardFooter className="justify-end">
            <TkButton onClick={goToImages}>Back to Images</TkButton>
          </TkCardFooter>
        )}
      </TkCard>
    </TkPageWrapper>
  )
}
