// frontend/src/components/harbor/ViewImageModal.vue
<template>
  <dialog :open="modelValue" class="modal" @close="close">
    <div class="modal-box max-w-3xl">
      <h3 class="font-bold text-lg mb-4">Image Details</h3>

      <div v-if="image">
        <!-- Basic Info -->
        <div class="grid grid-cols-2 gap-4 mb-6">
          <div>
            <label class="label">
              <span class="label-text font-semibold">Name</span>
            </label>
            <p class="text-lg">{{ image.name }}</p>
          </div>
          <div>
            <label class="label">
              <span class="label-text font-semibold">Tag</span>
            </label>
            <p class="text-lg">
              <span class="badge badge-outline">{{ image.tag }}</span>
            </p>
          </div>
        </div>

        <!-- Category and Protection -->
        <div class="grid grid-cols-2 gap-4 mb-6">
          <div>
            <label class="label">
              <span class="label-text font-semibold">Category</span>
            </label>
            <div
              class="badge badge-lg"
              :class="{
                'badge-info': image.category === 'core',
                'badge-success': image.category === 'custom',
                'badge-warning': image.category === 'user'
              }"
            >
              {{ image.category }}
            </div>
          </div>
          <div>
            <label class="label">
              <span class="label-text font-semibold">Protection Status</span>
            </label>
            <div v-if="image.protected" class="flex items-center gap-2">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-success" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
              </svg>
              <span>Protected from deletion</span>
            </div>
            <div v-else class="text-base-content/70">
              Not protected
            </div>
          </div>
        </div>

        <!-- URLs -->
        <div class="mb-6">
          <label class="label">
            <span class="label-text font-semibold">Registry URL</span>
          </label>
          <div class="mockup-code">
            <pre><code>{{ image.destination_url || `${image.registry}/${image.repository}:${image.tag}` }}</code></pre>
          </div>
        </div>

        <div v-if="image.source_url" class="mb-6">
          <label class="label">
            <span class="label-text font-semibold">Source URL</span>
          </label>
          <div class="mockup-code">
            <pre><code>{{ image.source_url }}</code></pre>
          </div>
        </div>

        <!-- Description -->
        <div v-if="image.description" class="mb-6">
          <label class="label">
            <span class="label-text font-semibold">Description</span>
          </label>
          <p class="text-base">{{ image.description }}</p>
        </div>

        <!-- Timestamps -->
        <div class="grid grid-cols-2 gap-4 mb-6">
          <div>
            <label class="label">
              <span class="label-text font-semibold">Mirror Date</span>
            </label>
            <p>{{ formatDate(image.mirror_date) }}</p>
          </div>
          <div>
            <label class="label">
              <span class="label-text font-semibold">Last Synced</span>
            </label>
            <p>{{ formatDate(image.last_synced) }}</p>
          </div>
        </div>

        <!-- Vulnerabilities -->
        <div v-if="image.vulnerabilities && Object.keys(image.vulnerabilities).length > 0" class="mb-6">
          <label class="label">
            <span class="label-text font-semibold">Vulnerability Summary</span>
          </label>
          <div class="flex gap-2">
            <div v-if="image.vulnerabilities.critical" class="stat bg-error/10 rounded p-2">
              <div class="stat-title text-xs">Critical</div>
              <div class="stat-value text-error text-lg">{{ image.vulnerabilities.critical }}</div>
            </div>
            <div v-if="image.vulnerabilities.high" class="stat bg-warning/10 rounded p-2">
              <div class="stat-title text-xs">High</div>
              <div class="stat-value text-warning text-lg">{{ image.vulnerabilities.high }}</div>
            </div>
            <div v-if="image.vulnerabilities.medium" class="stat bg-info/10 rounded p-2">
              <div class="stat-title text-xs">Medium</div>
              <div class="stat-value text-info text-lg">{{ image.vulnerabilities.medium }}</div>
            </div>
            <div v-if="image.vulnerabilities.low" class="stat bg-base-200 rounded p-2">
              <div class="stat-title text-xs">Low</div>
              <div class="stat-value text-lg">{{ image.vulnerabilities.low }}</div>
            </div>
          </div>
        </div>

        <!-- Metadata -->
        <div v-if="image.metadata && Object.keys(image.metadata).length > 0" class="mb-6">
          <label class="label">
            <span class="label-text font-semibold">Additional Metadata</span>
          </label>
          <div class="mockup-code">
            <pre><code>{{ JSON.stringify(image.metadata, null, 2) }}</code></pre>
          </div>
        </div>

        <!-- Size -->
        <div v-if="image.size_bytes" class="mb-6">
          <label class="label">
            <span class="label-text font-semibold">Image Size</span>
          </label>
          <p>{{ formatSize(image.size_bytes) }}</p>
        </div>
      </div>

      <!-- Actions -->
      <div class="modal-footer">
        <button @click="close" class="btn">Close</button>
      </div>
    </div>
    <div class="modal-backdrop" @click="close"></div>
  </dialog>
</template>

<script setup>
const props = defineProps({
  modelValue: {
    type: Boolean,
    default: false
  },
  image: {
    type: Object,
    default: null
  }
})

const emit = defineEmits(['update:modelValue', 'close'])

const close = () => {
  emit('update:modelValue', false)
  emit('close')
}

const formatDate = (dateString) => {
  if (!dateString) return 'Never'
  const date = new Date(dateString)
  return date.toLocaleDateString() + ' ' + date.toLocaleTimeString()
}

const formatSize = (bytes) => {
  if (!bytes) return 'Unknown'
  const sizes = ['Bytes', 'KB', 'MB', 'GB']
  if (bytes === 0) return '0 Bytes'
  const i = Math.floor(Math.log(bytes) / Math.log(1024))
  return Math.round(bytes / Math.pow(1024, i) * 100) / 100 + ' ' + sizes[i]
}
</script>

// frontend/src/components/harbor/ViewImageModal.tsx
/*
 * Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  TkDialogRoot,
  TkDialogContent,
  TkDialogHeader,
  TkDialogTitle,
  TkDialogFooter,
} from "thinkube-style/components/modals-overlays"
import { TkButton } from "thinkube-style/components/buttons-badges"
import { TkBadge } from "thinkube-style/components/buttons-badges"
import { TkCodeBlock } from "thinkube-style/components/feedback"
import { Lock } from "lucide-react"

interface HarborImage {
  id?: string
  name: string
  tag: string
  category: "core" | "custom" | "user"
  protected: boolean
  registry?: string
  repository?: string
  destination_url?: string
  source_url?: string
  description?: string
  mirror_date?: string
  last_synced?: string
  vulnerabilities?: {
    critical?: number
    high?: number
    medium?: number
    low?: number
  }
  metadata?: Record<string, unknown>
  size_bytes?: number
}

interface ViewImageModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  image: HarborImage | null
}

export function ViewImageModal({
  open,
  onOpenChange,
  image,
}: ViewImageModalProps) {
  const formatDate = (dateString?: string): string => {
    if (!dateString) return "Never"
    const date = new Date(dateString)
    return date.toLocaleDateString() + " " + date.toLocaleTimeString()
  }

  const formatSize = (bytes?: number): string => {
    if (!bytes) return "Unknown"
    const sizes = ["Bytes", "KB", "MB", "GB"]
    if (bytes === 0) return "0 Bytes"
    const i = Math.floor(Math.log(bytes) / Math.log(1024))
    return Math.round((bytes / Math.pow(1024, i)) * 100) / 100 + " " + sizes[i]
  }

  const getCategoryVariant = (
    category: string
  ): "default" | "success" | "warning" => {
    switch (category) {
      case "core":
        return "default"
      case "custom":
        return "success"
      case "user":
        return "warning"
      default:
        return "default"
    }
  }

  const close = () => {
    onOpenChange(false)
  }

  if (!image) return null

  return (
    <TkDialogRoot open={open} onOpenChange={onOpenChange}>
      <TkDialogContent className="max-w-3xl">
        <TkDialogHeader>
          <TkDialogTitle>Image Details</TkDialogTitle>
        </TkDialogHeader>

        <div className="space-y-6">
          {/* Basic Info */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="text-sm font-semibold text-foreground">
                Name
              </label>
              <p className="text-lg mt-1">{image.name}</p>
            </div>
            <div>
              <label className="text-sm font-semibold text-foreground">
                Tag
              </label>
              <p className="text-lg mt-1">
                <TkBadge variant="outline">{image.tag}</TkBadge>
              </p>
            </div>
          </div>

          {/* Category and Protection */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="text-sm font-semibold text-foreground">
                Category
              </label>
              <div className="mt-1">
                <TkBadge variant={getCategoryVariant(image.category)}>
                  {image.category}
                </TkBadge>
              </div>
            </div>
            <div>
              <label className="text-sm font-semibold text-foreground">
                Protection Status
              </label>
              {image.protected ? (
                <div className="flex items-center gap-2 mt-1">
                  <Lock className="h-5 w-5 text-success" />
                  <span>Protected from deletion</span>
                </div>
              ) : (
                <div className="mt-1 text-muted-foreground">Not protected</div>
              )}
            </div>
          </div>

          {/* URLs */}
          <div>
            <label className="text-sm font-semibold text-foreground">
              Registry URL
            </label>
            <TkCodeBlock className="mt-1">
              {image.destination_url ||
                `${image.registry}/${image.repository}:${image.tag}`}
            </TkCodeBlock>
          </div>

          {image.source_url && (
            <div>
              <label className="text-sm font-semibold text-foreground">
                Source URL
              </label>
              <TkCodeBlock className="mt-1">{image.source_url}</TkCodeBlock>
            </div>
          )}

          {/* Description */}
          {image.description && (
            <div>
              <label className="text-sm font-semibold text-foreground">
                Description
              </label>
              <p className="text-base mt-1">{image.description}</p>
            </div>
          )}

          {/* Timestamps */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="text-sm font-semibold text-foreground">
                Mirror Date
              </label>
              <p className="mt-1">{formatDate(image.mirror_date)}</p>
            </div>
            <div>
              <label className="text-sm font-semibold text-foreground">
                Last Synced
              </label>
              <p className="mt-1">{formatDate(image.last_synced)}</p>
            </div>
          </div>

          {/* Vulnerabilities */}
          {image.vulnerabilities &&
            Object.keys(image.vulnerabilities).length > 0 && (
              <div>
                <label className="text-sm font-semibold text-foreground">
                  Vulnerability Summary
                </label>
                <div className="flex flex-wrap gap-2 mt-1">
                  {image.vulnerabilities.critical !== undefined &&
                    image.vulnerabilities.critical > 0 && (
                      <TkBadge variant="destructive">
                        {image.vulnerabilities.critical} Critical
                      </TkBadge>
                    )}
                  {image.vulnerabilities.high !== undefined &&
                    image.vulnerabilities.high > 0 && (
                      <TkBadge variant="warning">
                        {image.vulnerabilities.high} High
                      </TkBadge>
                    )}
                  {image.vulnerabilities.medium !== undefined &&
                    image.vulnerabilities.medium > 0 && (
                      <TkBadge variant="default">
                        {image.vulnerabilities.medium} Medium
                      </TkBadge>
                    )}
                  {image.vulnerabilities.low !== undefined &&
                    image.vulnerabilities.low > 0 && (
                      <TkBadge variant="secondary">
                        {image.vulnerabilities.low} Low
                      </TkBadge>
                    )}
                </div>
              </div>
            )}

          {/* Metadata */}
          {image.metadata && Object.keys(image.metadata).length > 0 && (
            <div>
              <label className="text-sm font-semibold text-foreground">
                Additional Metadata
              </label>
              <TkCodeBlock className="mt-1">
                {JSON.stringify(image.metadata, null, 2)}
              </TkCodeBlock>
            </div>
          )}

          {/* Size */}
          {image.size_bytes && (
            <div>
              <label className="text-sm font-semibold text-foreground">
                Image Size
              </label>
              <p className="mt-1">{formatSize(image.size_bytes)}</p>
            </div>
          )}
        </div>

        <TkDialogFooter>
          <TkButton onClick={close}>Close</TkButton>
        </TkDialogFooter>
      </TkDialogContent>
    </TkDialogRoot>
  )
}
